## Tensors

In [1]:
import torch

Construct a $5x3$ tensor/matrix, uninitialized:

In [2]:
x = torch.empty(5,3)
x

tensor([[ 0.0000, -0.0000,  0.0000],
        [-0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])

Construct a randomly initialized matrix:

In [3]:
y = torch.rand((5,5))
print(y)

tensor([[0.0316, 0.3511, 0.1061, 0.0847, 0.8736],
        [0.2924, 0.5105, 0.9825, 0.0115, 0.5276],
        [0.0125, 0.8408, 0.8645, 0.3940, 0.0892],
        [0.3957, 0.1581, 0.8418, 0.8618, 0.1689],
        [0.4382, 0.3839, 0.0970, 0.9438, 0.5156]])


Construct a matrix filled with zero and of dtype long:

In [4]:
z = torch.zeros((5,3), dtype=torch.long)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a matrix directly from data:

In [5]:
l = [5.5, 3]
a = torch.Tensor(l)
print(a)

tensor([5.5000, 3.0000])


Create a new tensor based on an existing tensor

In [6]:
x = x.new_ones(x.shape)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 0.3807, -1.0796, -0.4761],
        [-0.3416,  1.7223,  0.4478],
        [-0.0988, -0.3686,  0.9016],
        [ 2.1198, -0.7754,  0.0675],
        [ 0.4665,  0.4154, -0.3492]])


Get size of the tensor:

In [7]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [8]:
m,n = x.size()
print('Size of tensor x: ({},{})'.format(m,n))

Size of tensor x: (5,3)


#### Operations

addition

In [9]:
y = torch.rand(5,3)
print(x + y)

tensor([[ 0.4340, -0.8958,  0.1774],
        [ 0.2825,  2.0687,  1.2882],
        [ 0.0187,  0.2096,  1.8032],
        [ 2.9748, -0.5114,  0.1757],
        [ 0.5802,  0.8094, -0.2002]])


or, we could do addition by using `torch.add()`

In [10]:
print(torch.add(x,y))

tensor([[ 0.4340, -0.8958,  0.1774],
        [ 0.2825,  2.0687,  1.2882],
        [ 0.0187,  0.2096,  1.8032],
        [ 2.9748, -0.5114,  0.1757],
        [ 0.5802,  0.8094, -0.2002]])


we also can do this

In [11]:
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.4340, -0.8958,  0.1774],
        [ 0.2825,  2.0687,  1.2882],
        [ 0.0187,  0.2096,  1.8032],
        [ 2.9748, -0.5114,  0.1757],
        [ 0.5802,  0.8094, -0.2002]])


In [12]:
print(result)

tensor([[ 0.4340, -0.8958,  0.1774],
        [ 0.2825,  2.0687,  1.2882],
        [ 0.0187,  0.2096,  1.8032],
        [ 2.9748, -0.5114,  0.1757],
        [ 0.5802,  0.8094, -0.2002]])


addition in place using `.add_()`

In [13]:
print(y)
y.add_(x)
print('new y: {}'.format(y))

tensor([[0.0533, 0.1838, 0.6535],
        [0.6241, 0.3464, 0.8404],
        [0.1175, 0.5782, 0.9015],
        [0.8550, 0.2641, 0.1083],
        [0.1137, 0.3940, 0.1491]])
new y: tensor([[ 0.4340, -0.8958,  0.1774],
        [ 0.2825,  2.0687,  1.2882],
        [ 0.0187,  0.2096,  1.8032],
        [ 2.9748, -0.5114,  0.1757],
        [ 0.5802,  0.8094, -0.2002]])


For indexing, PyTorch uses the same rule just like indexing in Numpy

In [14]:
print(y[:, 1])

tensor([-0.8958,  2.0687,  0.2096, -0.5114,  0.8094])


Resizing/reshaping tensor can be done using `torch.view`:

In [15]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If we have only __one__ element tensor, we can use `.item()` to get a Python number

In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.9624])
0.9624059796333313


#### Converting Torch Tensor to Numpy Array

In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b, type(b))

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


It is also affected if we do operation on the precedent Tensor

In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [20]:
import numpy as np

In [21]:
a = np.ones(5)
b = torch.from_numpy(a)

np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## Autograd

In [22]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [23]:
print(x.data)

tensor([[1., 1.],
        [1., 1.]])


In [24]:
print(x.grad, x.grad_fn) # we've created x ourselves

None None


In [25]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


because `y` was created as a result of an operation, hence it has `grad_fn`

In [26]:
print(y.grad_fn)

In [27]:
z = y * y * 3
print(z)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>)


We can also change `requires_grad` value in the middle of our work using `.requires_grad_()` in-place method

In [28]:
a = torch.randn(2,2)
a = ( (a*3) / (a-1) )
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [29]:
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


#### Gradient

In [30]:
print(x.grad)
out.backward()
print(x.grad)

None
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


using `retain_graph`

In [31]:
x = torch.ones(2,2, requires_grad=True)
y = x + 2
y.backward(torch.ones(2,2), retain_graph=True)
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])
