In [1]:
import torch

Construct a $5x3$ tensor/matrix, uninitialized:

In [2]:
x = torch.empty(5,3)
x

tensor([[ 0.0000e+00,  8.5899e+09,  0.0000e+00],
        [ 8.5899e+09,  5.6052e-45,  8.5899e+09],
        [ 0.0000e+00,  8.5899e+09,  0.0000e+00],
        [ 8.5899e+09, -1.7655e-12,  1.5849e+29],
        [-1.5135e-12, -1.5849e+29, -1.7713e-12]])

Construct a randomly initialized matrix:

In [3]:
y = torch.rand((5,5))
print(y)

tensor([[0.5596, 0.0772, 0.8433, 0.7974, 0.7919],
        [0.7062, 0.7549, 0.4395, 0.1580, 0.9234],
        [0.9516, 0.9369, 0.2530, 0.8856, 0.6346],
        [0.4534, 0.5656, 0.1201, 0.4169, 0.2862],
        [0.6831, 0.1837, 0.5246, 0.0224, 0.7648]])


Construct a matrix filled with zero and of dtype long:

In [4]:
z = torch.zeros((5,3), dtype=torch.long)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a matrix directly from data:

In [5]:
l = [5.5, 3]
a = torch.Tensor(l)
print(a)

tensor([5.5000, 3.0000])


Create a new tensor based on an existing tensor

In [6]:
x = x.new_ones(x.shape)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[-0.0162,  1.4251,  0.8727],
        [ 0.5465, -0.2901, -1.1724],
        [ 1.0916, -0.3507, -1.8038],
        [-1.7717,  0.0878,  1.2543],
        [ 0.0568,  0.6364, -0.4154]])


Get size of the tensor:

In [7]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [8]:
m,n = x.size()
print('Size of tensor x: ({},{})'.format(m,n))

Size of tensor x: (5,3)


#### Operations

addition

In [9]:
y = torch.rand(5,3)
print(x + y)

tensor([[ 0.5408,  2.0505,  1.5709],
        [ 1.1495, -0.0587, -0.5898],
        [ 1.1525, -0.0122, -0.8580],
        [-1.3247,  0.4010,  1.7579],
        [ 0.4164,  1.0522, -0.3221]])


or, we could do addition by using `torch.add()`

In [10]:
print(torch.add(x,y))

tensor([[ 0.5408,  2.0505,  1.5709],
        [ 1.1495, -0.0587, -0.5898],
        [ 1.1525, -0.0122, -0.8580],
        [-1.3247,  0.4010,  1.7579],
        [ 0.4164,  1.0522, -0.3221]])


we also can do this

In [11]:
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.5408,  2.0505,  1.5709],
        [ 1.1495, -0.0587, -0.5898],
        [ 1.1525, -0.0122, -0.8580],
        [-1.3247,  0.4010,  1.7579],
        [ 0.4164,  1.0522, -0.3221]])


In [12]:
print(result)

tensor([[ 0.5408,  2.0505,  1.5709],
        [ 1.1495, -0.0587, -0.5898],
        [ 1.1525, -0.0122, -0.8580],
        [-1.3247,  0.4010,  1.7579],
        [ 0.4164,  1.0522, -0.3221]])


addition in place using `.add_()`

In [13]:
print(y)
y.add_(x)
print('new y: {}'.format(y))

tensor([[0.5570, 0.6255, 0.6982],
        [0.6030, 0.2314, 0.5826],
        [0.0609, 0.3384, 0.9458],
        [0.4470, 0.3131, 0.5036],
        [0.3596, 0.4157, 0.0932]])
new y: tensor([[ 0.5408,  2.0505,  1.5709],
        [ 1.1495, -0.0587, -0.5898],
        [ 1.1525, -0.0122, -0.8580],
        [-1.3247,  0.4010,  1.7579],
        [ 0.4164,  1.0522, -0.3221]])


For indexing, PyTorch uses the same rule just like indexing in Numpy

In [14]:
print(y[:, 1])

tensor([ 2.0505, -0.0587, -0.0122,  0.4010,  1.0522])


Resizing/reshaping tensor can be done using `torch.view`:

In [15]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If we have only __one__ element tensor, we can use `.item()` to get a Python number

In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.6099])
0.6099287867546082


#### Converting Torch Tensor to Numpy Array

In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b, type(b))

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


It is also affected if we do operation on the precedent Tensor

In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [20]:
import numpy as np

In [21]:
a = np.ones(5)
b = torch.from_numpy(a)

np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
