In [1]:
import numpy as np
import torch

In [2]:
x = torch.rand(3, 2)
x

tensor([[0.6940, 0.9464],
        [0.9537, 0.5359],
        [0.4698, 0.8702]])

In [3]:
y = torch.ones(x.size())
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [4]:
z = x + y
z

tensor([[1.6940, 1.9464],
        [1.9537, 1.5359],
        [1.4698, 1.8702]])

In [5]:
z[0]

tensor([1.6940, 1.9464])

In [6]:
z[:, :1]

tensor([[1.6940],
        [1.9537],
        [1.4698]])

In [7]:
z[:, 1:]

tensor([[1.9464],
        [1.5359],
        [1.8702]])

Different between `add()` and `add_()`

In [8]:
z.add(10)

tensor([[11.6940, 11.9464],
        [11.9537, 11.5359],
        [11.4698, 11.8702]])

In [9]:
z

tensor([[1.6940, 1.9464],
        [1.9537, 1.5359],
        [1.4698, 1.8702]])

In [10]:
z.add_(10)

tensor([[11.6940, 11.9464],
        [11.9537, 11.5359],
        [11.4698, 11.8702]])

In [11]:
z

tensor([[11.6940, 11.9464],
        [11.9537, 11.5359],
        [11.4698, 11.8702]])

In [12]:
z.size()

torch.Size([3, 2])

In [13]:
z.resize(2,3)

/Users/syahrulhamdani/anaconda3/envs/100DaysOfMLCode/lib/python3.6/site-packages/torch/tensor.py:263: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


tensor([[11.6940, 11.9464, 11.9537],
        [11.5359, 11.4698, 11.8702]])

Different between `reshape()` and `reshape_()`

In [14]:
z

tensor([[11.6940, 11.9464],
        [11.9537, 11.5359],
        [11.4698, 11.8702]])

In [15]:
z.resize_(2,3)

tensor([[11.6940, 11.9464, 11.9537],
        [11.5359, 11.4698, 11.8702]])

### Numpy to Torch and back

- to create a tensor from a Numpy array -> `torch.from_numpy()`
- to convert a tensor to a Numpy -> `.numpy()`

In [16]:
a = np.random.rand(4,3)
a

array([[0.79694577, 0.90804776, 0.40362851],
       [0.88128734, 0.60813404, 0.77323731],
       [0.33277689, 0.42690625, 0.41470782],
       [0.94998843, 0.43793298, 0.76462789]])

In [17]:
b = torch.from_numpy(a)
b

tensor([[0.7969, 0.9080, 0.4036],
        [0.8813, 0.6081, 0.7732],
        [0.3328, 0.4269, 0.4147],
        [0.9500, 0.4379, 0.7646]], dtype=torch.float64)

In [18]:
b.numpy()

array([[0.79694577, 0.90804776, 0.40362851],
       [0.88128734, 0.60813404, 0.77323731],
       [0.33277689, 0.42690625, 0.41470782],
       [0.94998843, 0.43793298, 0.76462789]])